-record(point, {coords, value}).
-record(axes, {size, time, measurements = []}).
-record(family, {initial, grow}).
-record(frontier, {inert, ert}).
-import(measure, [measure/4]).
-import(timing, [time1/1]).
