-record(point, {coords, value}).
-record(axes, {size, time, measurements = [], repeat = 0, outliers = 0, name = "untitled"}).
-record(family, {initial, grow, warmup = false}).
-record(frontier, {inert, ert}).
-import(measure, [measure/4]).
-import(measure_java, [measure_java/4]).
-import(timing, [time1/1]).
